CREATE DATABASE BAITHI

CREATE TABLE HANG (
	MAHANG CHAR(4) NOT NULL,
	TENHANG VARCHAR(20),
	NUOCSX VARCHAR(20),
	CHUHANG VARCHAR(40),
	CONSTRAINT PK_HANG PRIMARY KEY (MAHANG)
)

CREATE TABLE KHACHHANG (
	MAKH CHAR(5) NOT NULL,
	TENKH VARCHAR(40),
	NGSINH SMALLDATETIME,
	GIOITINH CHAR(3),
	NGDK SMALLDATETIME,
	CONSTRAINT PK_KH PRIMARY KEY (MAKH)
)

CREATE TABLE DONGXE (
	MADONG CHAR(4) NOT NULL,
	MAHANG CHAR(4),
	TENDONG VARCHAR(40),
	LOAINL CHAR(4),
	LOAIPIN CHAR(20),
	NGRM SMALLDATETIME,
	CONSTRAINT PK_DONGXE PRIMARY KEY (MADONG)
)

CREATE TABLE XE (
	MAXE CHAR(4) NOT NULL,
	MADONG CHAR(4),
	MAKH CHAR(5) ,
	BIENSO VARCHAR(20),
	NGMUA SMALLDATETIME,
	NGBD SMALLDATETIME,
	SOCHO TINYINT,
	CONSTRAINT PK_XE PRIMARY KEY (MAXE,MADONG,MAKH)
)

ALTER TABLE DONGXE ADD CONSTRAINT FK_DONGXE FOREIGN KEY (MAHANG) REFERENCES HANG(MAHANG)
ALTER TABLE XE ADD CONSTRAINT FK_XE01 FOREIGN KEY (MADONG) REFERENCES DONGXE(MADONG)
ALTER TABLE XE ADD CONSTRAINT FK_XE02 FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

SET DATEFORMAT DMY;

INSERT INTO HANG VALUES ('H001','Dat bike','Viet nam','Nguyen Ba Canh Son')
INSERT INTO HANG VALUES ('H002','VinFast','Viet nam','Pham Nhat Vuong')
INSERT INTO HANG VALUES ('H003','Kia','Han quoc','Kim Cheol-ho')
select*from HANG

INSERT INTO KHACHHANG VALUES('KH001','Le Thi Chi','23/09/1999','Nu','25/05/2020')
INSERT INTO KHACHHANG VALUES('KH002','Huynh Man Dat','13/09/2000','Nam','24/06/2020')
INSERT INTO KHACHHANG VALUES('KH003','Nguyen Minh Ha','15/06/1999','Nu','13/07/2021')
SELECT*FROM KHACHHANG

INSERT INTO DONGXE VALUES ('D001','H001','Dat bike weaver 200','Dien','Lithium-ion','27/11/2021')
INSERT INTO DONGXE VALUES ('D002','H002','VF e34','Dien','Lithium-ion','15/10/2021')
INSERT INTO DONGXE VALUES ('D003','H002','Lux A2.0','Xang','null','28/07/2019')
SELECT*FROM DONGXE


INSERT INTO XE VALUES ('X001','D001','KH001','51-T1 063.25','20/05/2022','20/07/2022',2)
INSERT INTO XE VALUES ('X002','D002','KH002','30V 123.08','19/06/2022','15/08/2022',4)
INSERT INTO XE VALUES ('X003 ','D003','KH003','51-T2 010.04','13/07/2022','20/08/2022',4)
SELECT*FROM XE

--------
--cau3
ALTER TABLE DONGXE 
ADD CONSTRAINT CHECK_DONGXE 
CHECK ((LOAINL <>'Dien' AND LOAIPIN='null') or LOAINL='Dien')


--cau4
GO
CREATE TRIGGER TRG_UP_DONGXE ON DONGXE
FOR UPDATE 
AS
BEGIN
		UPDATE XE
		SET SOCHO=2
		WHERE MAXE IN 
		(SELECT B.MAXE FROM INSERTED AS A,XE AS B
			WHERE B.MADONG=A.MADONG AND LOAINL='Dien' AND YEAR(NGRM)<2018)
END;
---------
GO
CREATE TRIGGER TRG_IN_UP_XE ON XE
FOR INSERT,UPDATE
AS
BEGIN
	IF(EXISTS (
	SELECT*FROM INSERTED AS A, DONGXE AS B
	WHERE A.MADONG=B.MADONG AND YEAR(NGRM)<2018 AND LOAINL='Dien' AND SOCHO!=2
	))
	BEGIN
		PRINT 'LOI:  LOI SO CHO CUA XE'
		ROLLBACK
	END
END

--UPDATE XE
--SET SOCHO=2
--WHERE MAXE='X001'

--UPDATE DONGXE 
--SET NGRM='27/11/2021'
--WHERE MADONG='D001'


--cau5
SELECT A.MAKH,TENKH
FROM KHACHHANG A,DONGXE,XE
WHERE A.MAKH=XE.MAKH AND DONGXE.MADONG=XE.MADONG AND LOAINL='Dien' AND YEAR(NGBD)>=2022 AND MONTH(NGBD)>=5
ORDER BY NGBD DESC

--CAU6
SELECT MADONG, TENDONG
FROM DONGXE
WHERE MADONG=(SELECT TOP 1 x.MADONG FROM XE X, DONGXE D,HANG H 
WHERE (D.LOAINL='Dien') and (h.TENHANG='Vinfast') and (year(x.NGBD)=2022) and (x.MADONG=d.MADONG) and (d.MAHANG=h.MAHANG)
group by x.MADONG
order by count(x.MADONG) desc)


-----
--CAU7

SELECT A.MADONG  FROM HANG,DONGXE AS A
WHERE HANG.MAHANG=A.MAHANG AND TENHANG='VinFast' AND LOAINL='Dien'
except 
select B.MADONG  FROM XE,DONGXE AS B
WHERE B.MADONG=XE.MADONG 


---
--CAU8
SELECT*FROM KHACHHANG WHERE  NOT EXISTS
(
	SELECT*FROM DONGXE JOIN HANG ON DONGXE.MAHANG=HANG.MAHANG WHERE LOAINL='Dien' AND TENHANG='VinFast' and NOT EXISTS 
	(
		SELECT*FROM XE WHERE XE.MAKH=KHACHHANG.MAKH AND XE.MADONG=DONGXE.MADONG
	)
)















